[*]
# Global defaults applied to all model workers (router mode)

# Hardware & Speed Optimizations
ngl = 99                 ; Fully offload all layers to your 48GB VRAM
flash-attn = true        ; Force hardware-accelerated attention matrixing
threads = 16             ; Adjust to match your physical CPU core count
parallel = 1             ; Adjust to match your physical GPU count
mlock = true             ; Lock model into RAM to avoid page faults
stop-timeout = 2          ; Force-kill child process after graceful shutdown timeout in seconds (default: 10)
sleep-idle-seconds = 300  ; Unload weights on child process

# Context & Memory Handling
ctx-size = 131072        ; Sets a uniform 128K context floor for both models
no-kv-offload = false    ; Ensure the KV cache stays inside your fast VRAM

# Universal Template Handling
reasoning = auto           ; Automatically strips and parses <think> tags for all models
reasoning-budget = 1024    ; Sets a uniform reasoning budget for all models


[qwen3.5-4B]
model = /models/Qwen3.5-4B/Qwen3.5-4B-UD-Q4_K_XL.gguf
mmproj = /models/Qwen3.5-4B/mmproj-BF16.gguf
#ctx-size = 131072
ctx-size = 32768
batch-size = 2048
temp = 0.2
top-p = 0.85
repeat-penalty = 1.05
; parallel = 2

[gemma-4-31B]
# https://huggingface.co/unsloth/gemma-4-31B-it-GGUF
model = /models/gemma-4-31B-it/gemma-4-31B-it-UD-Q4_K_XL.gguf
mmproj = /models/gemma-4-31B-it/mmproj-BF16.gguf
model-draft = /models/gemma-4-31B-it/mtp-gemma-4-31B-it.gguf
n-predict = 8192
batch-size = 4096
temp = 0.6
top-p = 0.90
repeat-penalty = 1.1
spec-type = draft-mtp
spec-draft-n-max = 4
spec-draft-p-min = 0.75
reasoning-budget = 2048


[qwen3.6-35B]
model = /models/Qwen3.6-35B-A3B-MTP/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
mmproj = /models/Qwen3.6-35B-A3B-MTP/mmproj-BF16.gguf
n-predict = 8192
batch-size = 4096
temp = 0.6
top-p = 0.90
repeat-penalty = 1.1
spec-type = draft-mtp
spec-draft-n-max = 4
spec-draft-p-min = 0.75

[qwen3.6-27B]
model = /models/Qwen3.6-27B-MTP/Qwen3.6-27B-UD-Q4_K_XL.gguf
mmproj = /models/Qwen3.6-27B-MTP/mmproj-BF16.gguf
batch-size = 2048
temp = 0.2
top-p = 0.80
repeat-penalty = 1.05
spec-type = draft-mtp
spec-draft-n-max = 4
spec-draft-p-min = 0.75
