# llama.cpp Python server (llama-cpp-python + Jupyter)

services:
  llamacpp-server-py:
    image: ${REGISTRY:-llamacpp-server-python}/llamacpp-server-py:${LLAMA_CPP_VERSION:-0.3.34}
    shm_size: '8gb'
    entrypoint: ${ENTRYPOINT:-/app/scripts/entrypoint.llamacpp.sh}
    ulimits:
      memlock: -1
    build:
        network: host
        context: .
        dockerfile: compose/llama/Dockerfile.llamacpp-server-python
        args:
          BASE_IMAGE: ${BASE_IMAGE:-ghcr.io/ggml-org/llama.cpp:full-cuda-b4738}
          LLAMA_CPP_VERSION: ${LLAMA_CPP_VERSION:-0.3.34}
          REQUIREMENTS_FILE: ${REQUIREMENTS_FILE:-requirements-dev.txt}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_ID:-0}"]
              capabilities: [gpu]
    ports:
      - 18000:8000
      - 18888:8888
    volumes:
      - ${MODELS:-./models}:/models
      - ./scripts/entrypoint.llamacpp.sh:/app/scripts/entrypoint.llamacpp.sh
      - ./workspace:/app/workspace
      - .jupyter:/root/.jupyter
    environment:
      # alternatively, you can use "LLAMA_ARG_MODEL_URL" to download the model
      LLM_CONFIG: ${LLM_CONFIG:-config.json}
